name: kolektt
description: A Flutter app for record collectors
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.3.0
  camera: ^0.11.1
  barcode_scan2: ^4.5.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  fl_chart: ^0.70.2
  audioplayers: ^6.2.0
  modal_bottom_sheet: ^3.0.0
  webview_flutter: ^4.10.0
  supabase_flutter: ^2.8.4
  transparent_image: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/