name: kolektt
description: A Flutter app for record collectors
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  http: ^1.3.0
  camera: ^0.10.0
  barcode_scan2: ^4.2.0
  sqflite: ^2.0.0
  path_provider: ^2.0.0
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  fl_chart: ^0.70.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/