name: kolektt
description: A Flutter app for record collectors
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.3.0
  logger: ^2.0.0
  barcode_scan2: ^4.5.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  fl_chart: ^0.70.2
  audioplayers: ^6.2.0
  flutter_cupernino_bottom_sheet: ^1.0.8
  webview_flutter: ^4.10.0
  supabase_flutter: ^2.8.4
  transparent_image: ^2.0.1
  image_picker: ^1.1.2
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  crypto: ^3.0.6
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cunning_document_scanner: ^1.2.3
  google_generative_ai: ^0.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

  fonts:
    - family: PlusJakartaSans
      fonts:
#        - asset: assets/fonts/PlusJakartaSans-Thin.ttf
#          weight: 100
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
#        - asset: assets/fonts/PlusJakartaSans-Black.ttf
#          weight: 900
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
          style: italic
dev_dependencies:
  change_app_package_name: ^1.5.0
