// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVJVz-DH2qLaOWAoIj4i1FCQOJPDdvVrI',
    appId: '1:418323176401:web:686c9e8c703046bd029ef0',
    messagingSenderId: '418323176401',
    projectId: 'kolektt-aa42b',
    authDomain: 'kolektt-aa42b.firebaseapp.com',
    storageBucket: 'kolektt-aa42b.firebasestorage.app',
    measurementId: 'G-DRE5TSGEV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUp9Sj5k21SbY0N_4tQsR6RYHxqerH2Tk',
    appId: '1:418323176401:android:ce716c459b6dbcd1029ef0',
    messagingSenderId: '418323176401',
    projectId: 'kolektt-aa42b',
    storageBucket: 'kolektt-aa42b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOS3zoZ0hb6oAlG_tYYe91Fxpfk0gWaOw',
    appId: '1:418323176401:ios:fbc402a6ae759c39029ef0',
    messagingSenderId: '418323176401',
    projectId: 'kolektt-aa42b',
    storageBucket: 'kolektt-aa42b.firebasestorage.app',
    iosBundleId: 'com.kolektt.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOS3zoZ0hb6oAlG_tYYe91Fxpfk0gWaOw',
    appId: '1:418323176401:ios:812a8fd0770c5c74029ef0',
    messagingSenderId: '418323176401',
    projectId: 'kolektt-aa42b',
    storageBucket: 'kolektt-aa42b.firebasestorage.app',
    iosBundleId: 'com.example.kolektt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVJVz-DH2qLaOWAoIj4i1FCQOJPDdvVrI',
    appId: '1:418323176401:web:643577a72580dd32029ef0',
    messagingSenderId: '418323176401',
    projectId: 'kolektt-aa42b',
    authDomain: 'kolektt-aa42b.firebaseapp.com',
    storageBucket: 'kolektt-aa42b.firebasestorage.app',
    measurementId: 'G-4MLTZHKRSW',
  );
}
